spring.application.name=trainer-panel

server.port = 8085
# listen on all network interfaces
server.address=0.0.0.0
# PostgreSQL data source
spring.datasource.url = ${DB_URL:jdbc:postgresql://localhost:5432/gym_management}
spring.datasource.username = ${DB_USERNAME:postgres}
spring.datasource.password = ${DB_PASSWORD:Vishwas@2002}
spring.datasource.driver-class-name = org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Error Handling
server.error.include-message=never
server.error.include-stacktrace=never

# JWT Secret
jwt.secret=${JWT_SECRET_KEY:your-256-bit-secret-here-change-in-prod-your-256-bit-secret-here}

# CORS
spring.web.cors.allowed-origins=${FRONTEND_URL:http://localhost:5173},http://127.0.0.1:5173,http://localhost:3000
