spring.application.name=trainer-panel

server.port = 8084
# listen on all network interfaces
server.address=0.0.0.0
# PostgreSQL data source
spring.datasource.url = jdbc:postgresql://localhost:5432/gym_management
spring.datasource.username = postgres
spring.datasource.password = Vishwas@2002
spring.datasource.driver-class-name = org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
